update pkg

diff --git a/debian/postinst b/debian/postinst
--- a/debian/postinst
+++ b/debian/postinst
@@ -2,8 +2,11 @@
 
 CONFIG_FILE="/etc/greetd/config.toml"
 
-# Replace the [terminal] command
-sed -i 's|^\([[:space:]]*command = \).*qtgreet.*|\1"qtgreet --cmd ''{{ command }}''"|' "$CONFIG_FILE"
+if [ ! -f "$CONFIG_FILE" ]; then
+    echo "❌ Error: $CONFIG_FILE not found."
+    exit 1
+fi
 
-# Replace the [default_session] command
-sed -i 's|^\([[:space:]]*command = \).*dbus-run-session.*|\1"dbus-run-session -- /usr/bin/startplasma-wayland"|' "$CONFIG_FILE"
+sed -i "/^\[terminal\]/,/^\[/ s|^\( *command = \).*|\1\"qtgreet --cmd '{{ command }}'\"|" "$CONFIG_FILE"
+
+sed -i '/^\[default_session\]/,/^\[/ s|^\( *command = \).*|\1"dbus-run-session Hyprland"|' "$CONFIG_FILE"
